# GNU Make project makefile autogenerated by Premake
ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifndef CC
  CC = gcc
endif

ifndef CXX
  CXX = g++
endif

ifndef AR
  AR = ar
endif

ifeq ($(config),debug)
  OBJDIR     = obj/Debug/HDRfromLDRcollection
  TARGETDIR  = .
  TARGET     = $(TARGETDIR)/HDRfromLDRcollection
  DEFINES   += -DDEBUG
  INCLUDES  += -Iinclude -I/usr/include/OpenEXR -I/usr/include/opencv -Iinclude/Bibliotheque_SVD -Iinclude/Bibliotheque_HDR
  CPPFLAGS  += -MMD -MP $(DEFINES) $(INCLUDES)
  CFLAGS    += $(CPPFLAGS) $(ARCH) -g -ggdb -Wall -Wextra
  CXXFLAGS  += $(CFLAGS) 
  LDFLAGS   += -L../ -L/usr/lib -L./
  LIBS      += -lcv -lhighgui -lIlmImf -lIlmThread -lImath
  RESFLAGS  += $(DEFINES) $(INCLUDES) 
  LDDEPS    += 
  LINKCMD    = $(CXX) -o $(TARGET) $(OBJECTS) $(LDFLAGS) $(RESOURCES) $(ARCH) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),release)
  OBJDIR     = obj/Release/HDRfromLDRcollection
  TARGETDIR  = .
  TARGET     = $(TARGETDIR)/HDRfromLDRcollection
  DEFINES   += -DNDEBUG
  INCLUDES  += -Iinclude -I/usr/include/OpenEXR -I/usr/include/opencv -Iinclude/Bibliotheque_SVD -Iinclude/Bibliotheque_HDR
  CPPFLAGS  += -MMD -MP $(DEFINES) $(INCLUDES)
  CFLAGS    += $(CPPFLAGS) $(ARCH) -O2 -ggdb -Wall -Wextra
  CXXFLAGS  += $(CFLAGS) 
  LDFLAGS   += -s -L../ -L/usr/lib -L./
  LIBS      += -lcv -lhighgui -lIlmImf -lIlmThread -lImath
  RESFLAGS  += $(DEFINES) $(INCLUDES) 
  LDDEPS    += 
  LINKCMD    = $(CXX) -o $(TARGET) $(OBJECTS) $(LDFLAGS) $(RESOURCES) $(ARCH) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

OBJECTS := \
	$(OBJDIR)/svd.o \
	$(OBJDIR)/cheb.o \
	$(OBJDIR)/kl.o \
	$(OBJDIR)/gaussj.o \
	$(OBJDIR)/matrix.o \
	$(OBJDIR)/nrutil.o \
	$(OBJDIR)/fourn.o \
	$(OBJDIR)/mrq.o \
	$(OBJDIR)/responseFunctionEstimator.o \
	$(OBJDIR)/MTB.o \
	$(OBJDIR)/solveur_Debevec.o \
	$(OBJDIR)/mainLdrToHdr.o \

RESOURCES := \

SHELLTYPE := msdos
ifeq (,$(ComSpec)$(COMSPEC))
  SHELLTYPE := posix
endif
ifeq (/bin,$(findstring /bin,$(SHELL)))
  SHELLTYPE := posix
endif

.PHONY: clean prebuild prelink

all: $(TARGETDIR) $(OBJDIR) prebuild prelink $(TARGET)

$(TARGET): $(GCH) $(OBJECTS) $(LDDEPS) $(RESOURCES)
	@echo Linking HDRfromLDRcollection
	$(SILENT) $(LINKCMD)
	$(POSTBUILDCMDS)

$(TARGETDIR):
	@echo Creating $(TARGETDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(TARGETDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(TARGETDIR))
endif

$(OBJDIR):
	@echo Creating $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif

clean:
	@echo Cleaning HDRfromLDRcollection
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -f  $(TARGET)
	$(SILENT) rm -rf $(OBJDIR)
else
	$(SILENT) if exist $(subst /,\\,$(TARGET)) del $(subst /,\\,$(TARGET))
	$(SILENT) if exist $(subst /,\\,$(OBJDIR)) rmdir /s /q $(subst /,\\,$(OBJDIR))
endif

prebuild:
	$(PREBUILDCMDS)

prelink:
	$(PRELINKCMDS)

ifneq (,$(PCH))
$(GCH): $(PCH)
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
endif

$(OBJDIR)/svd.o: include/Bibliotheque_SVD/svd.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/cheb.o: include/Bibliotheque_SVD/cheb.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/kl.o: include/Bibliotheque_SVD/kl.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/gaussj.o: include/Bibliotheque_SVD/gaussj.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/matrix.o: include/Bibliotheque_SVD/matrix.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/nrutil.o: include/Bibliotheque_SVD/nrutil.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/fourn.o: include/Bibliotheque_SVD/fourn.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/mrq.o: include/Bibliotheque_SVD/mrq.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/responseFunctionEstimator.o: src/responseFunctionEstimator.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/MTB.o: src/MTB.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/solveur_Debevec.o: src/solveur_Debevec.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/mainLdrToHdr.o: mainLdrToHdr.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<

-include $(OBJECTS:%.o=%.d)
